# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180319_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('comment_article', 'Can comment an article'), ('create_article', 'Can create an article'), ('publish_article', 'Can publish article'))},
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_logged_in_user',
            field=models.BooleanField(default=False),
        ),
    ]
